# Create a release for the subfolder which has the latest changes only
# https://stackoverflow.com/questions/45907185/github-release-a-specific-folder
name: Create Release

on:
  # Triggers on changes and PRs to `master`
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "create_release"
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # create a new branch
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'TODO-generate-branch-name-from-changed-folder'

      - name: Delete all except relevant folder
        run: |
          git checkout 'TODO-generate-branch-name-from-changed-folder'
          CHANGED_FOLDERS=$(git log -1 --name-only --oneline HEAD~..HEAD | tail -n +2 | cut -d / -f 1 | sort | uniq)
          NUM_CHANGED=$(echo $CHANGED_FOLDERS | wc -l)
          if [ $NUM_CHANGED != "1" ]; then 
            echo "This only works when there is only one implementation changed; found $CHANGED_FOLDERS"
            exit 1
          fi
          SUBFOLDERS=$(find . -maxdepth 1 -mindepth 1 \! -name '.??*' -type d)
          for FOLDER in $SUBFOLDERS; do
            echo $FOLDER
          done
